# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 155273575ef8049b8f7a0e7dbb0aec2eb0be3c67546f863f61e3d1580ce5ae4595aad9bc3c0d4184525d92a5b175e3e789a3b488f9d762e4702b60ab95878e48

test:
  secret_key_base: 8cd7868193427668d8ad5bdb66154dee9acf895efa94ac0169b2059ef3ca5507099e5b89bc96b600092bb3882c1fc575ae47918c1936c63489a65eef086912a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
